/*
SETTING HEADER
*/
#ifndef SETTING_H
#define SETTING_H

#define MAX_SIZE 1000
#define MAX_LENGTH 100 

extern int MAX_ATHLETE_PARTICIPATION;
extern int MIN_EVENT_PARTICIPATION;
extern int RANKING_ATHLETE_RANGE[MAX_LENGTH][2];
extern int RANKING_SELECT_COUNT[MAX_LENGTH];
extern int RANKING_SCORE_RULE[MAX_LENGTH][MAX_SIZE];
 
// view
void settingView();

#endif
